
default: &default
  adapter: postgis
  encoding: unicode
  postgis_extension: postgis      
  schema_search_path: "public,postgis"
  pool: 5
  username: estevao           
  password: estevao
  su_username: estevao     # a superuser for the database
  su_password: estevao  # the superuser's password

development:
  <<: *default
  database: segmentacao-rodovias_development
test:
  <<: *default
  database: segmentacao-rodovias_test

production:
  <<: *default
  database: segmentacao-rodovias_production
  username: segmentacao-rodovias
  password: <%= ENV['SEGMENTACAO-RODOVIAS_DATABASE_PASSWORD'] %>
