
default: &default
  adapter: postgresql
  encoding: unicode
  postgis_extension: postgis
  schema_search_path: public, postgis
  pool: 5 
  username: root           
  password: root 

development:
  <<: *default
  database: segmentacao-rodovias_development
test:
  <<: *default
  database: segmentacao-rodovias_test

production:
  <<: *default
  database: segmentacao-rodovias_production
  username: segmentacao-rodovias
  password: <%= ENV['SEGMENTACAO-RODOVIAS_DATABASE_PASSWORD'] %>
